[package]
name = "trident"
version = "0.1.0"
authors = ["benjamin <benji.lef76@gmail.com>"]
edition = "2018"

[profile.dev]
overflow-checks = false 

[dependencies.ocl]
version = "0.19.3"

[dependencies.num-complex]
version = "0.3.0"
